services:
  app:
    build: .
    ports:
      - "${PORT}:5000"
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: "postgres:17"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Saurabh@123
      - POSTGRES_DB=SDM
